target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'wizardly', :git => 'https://github.com/daugeldauge/wizardly', :branch => 'gitpodspec'
end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end