target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|

      # Disable signing for all synthetic pods KT-54314

      deployment_target_split = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']&.split('.')
      deployment_target_major = deployment_target_split&.first&.to_i
      deployment_target_minor = deployment_target_split&.second&.to_i

      if deployment_target_major && deployment_target_minor then
        if deployment_target_major < 11 || (deployment_target_major == 11 && deployment_target_minor < 0) then
            version = "#{11}.#{0}"
            puts "Deployment target for #{target} #{config} has been raised to #{version}. See KT-57741 for more details"
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = version
        end
      end
    end
  end
end